server:
  port: 8088
  compression:
    enabled: false
seata:
  enabled: true
  application-id: applicationName
  tx-service-group: aurora_blog_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  main:
    allow-circular-references: true
  redis:
    database: 1
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-active: 15
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora_blog?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Cqy19981202
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: aurora-admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
mybatis:
  mapper-locations: classpath:mapper/**
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 自定义的配置
aurora:
  snow-flake-worker-id: 2
  snow-flake-datacenter-id: 12
  account:
    mail-verify-account-expiration-time: 120000
    mail-verify-account-prefix-path: http://localhost:8088/admin/verifyAccount/
  default:
    avatar: https://picture.xcye.xyz/avatar.jpg
    role: ROLE_user
    permission: user
    nickname: aurora-new

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    xyz.xcye.web.common.service.feign.MessageLogFeignService: DEBUG

feign:
  circuitbreaker:
    enabled: true
    group:
      enabled: true