server:
  port: 7075
seata:
  enabled: true
  application-id: applicationName
  tx-service-group: aurora_blog_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"

spring:
  mail:
    host: smtp.qq.com
    username: 2291308094@qq.com
    password: uutqhjyodxtrdiea
    protocol: smtps
    properties.mail.smtp.port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttlls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  main:
    allow-circular-references: true
  redis:
    database: 1
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-active: 15
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora_comment?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Cqy19981202
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: aurora-comment
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
mybatis:
  mapper-locations: classpath:mapper/**
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"


# 自定义的配置

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


feign:
  client:
    config:
      aurora-message:
        connectTimeout: 100000
        readTimeout: 7000
  httpclient:
    enabled: true

aurora:
  snow-flake-datacenter-id: 5
  snow-flake-worker-id: 23
logging:
  level:
    xyz.xcye.aurora.feign.MessageLogFeignService: debug